timezone: Europe/London
livereload: true
title: Barnsley Gymnastics Club
description: An exciting and vibrant gymnastics club specializing in  girls artistic, acro, tumbling and pre-school. We are affiliated with British Gymnastics.
theme:

sass:
    sass_dir: _sass
    style: compressed

optional_front_matter:
    remove_originals: true

defaults:
    -
        scope:
            path: "" 
            type: "pages"
        values:
            layout: "page"
plugins:
    - jekyll-seo-tag
    - jekyll-sitemap
    - jekyll-feed
    - jekyll-coffeescript
    - jekyll-optional-front-matter